version: '3.7'

services:
  redis-node1:
    image: redis:6.2-alpine
    container_name: redis-node1
    ports:
      - "6379:6379"
    volumes:
      - ./tls:/tls
      - ./redis-node1/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - redis-cluster

  redis-node2:
    image: redis:6.2-alpine
    container_name: redis-node2
    ports:
      - "6380:6379"
    volumes:
      - ./tls:/tls
      - ./redis-node2/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - redis-cluster

  redis-node3:
    image: redis:6.2-alpine
    container_name: redis-node3
    ports:
      - "6381:6379"
    volumes:
      - ./tls:/tls
      - ./redis-node3/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - redis-cluster

networks:
  redis-cluster:
    driver: bridge

